project:
  project_id: your-project-id
  project_number: 1234567890123
  region: us-central1

recognition:
  bundle_filename: similarity_results.jsonl
  catalog_id : a-catalog-id-sample
  endpoint_id: '002'
  categories: ['None', 'Bread', 'Cofee', 'Meat', 'Soft Drinks', 'Tea']