project:
  project_id: your-project-id
  project_number: 1234567890123
  region: us-central1

recognition:
  bundle_filename: similarity_results.jsonl
  catalog_id : a-catalog-id-sample
  endpoint_id: '002'
  categories: ['None', 'Bread', 'Cofee', 'Meat', 'Soft Drinks', 'Tea']

catalog:
  update_bucket: neon-camera-403606-catalog-images

matching_engine:
  api_endpoint: sample.vdb.vertexai.goog
  index_enpoint: projects/project_id/locations/us-central1/indexEndpoints/id
  deployed_index_id : deployed_index_id